name: Check Links

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - "content/**"
      - "lychee.toml"

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v2
        with:
          args: --config lychee.toml --no-progress "./content/**/*.md"
          fail: true
